apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.podName }}
  labels:
    k8s-app: {{ .Values.podName }}
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      k8s-app: {{ .Values.podName }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.podName }}
        version: {{ .Values.tag }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.pullSecret }}
      containers:
      - image: {{ .Values.image }}:{{ .Values.tag }}
        name: {{ .Values.podName }}
        imagePullPolicy: Always
        env:
        - name: HTTP_PORT
          value: '80'
        - name: BEHIND_REVERSE_PROXY
          value: "false"
        - name: PROD
          value: "true"
        - name: DEMO
          value: "false"
        - name: UNMS_REDISDB_HOST
          value: "unms-redis.unms.svc.k8s.domain.tld"
        - name: UNMS_PG_HOST
          value: "unms-db.unms.svc.k8s.domain.tld"
        - name: UNMS_RABBITMQ_HOST
          value: "unms-rbmq.unms.svc.k8s.domain.tld"
        volumeMounts:
        - name: storage-folder
          mountPath: /home/app/unms/data
        resources:
          requests:
            cpu: 0.5
            memory: 400
      volumes:
        - name: storage-folder
          persistentVolumeClaim:
            claimName: {{ .Release.Namespace }}-storage
